config/routes.rb
Rails.application.routes.draw do
  resources :avalon_items
  resources :avalon_item_notes, only: [:new, :create]
  resources :people
  resources :performances
  resources :performance_notes, only: [:new, :create]
  resources :policies
  resources :recording_contributors
  resources :recording_notes, only: [:new, :create]
  resources :recordings
  resources :tracks
  resources :contracts

  get '/nav/search', to: 'nav#search', as: "search"
  get '/date_search', to: 'nav#date_search_get', as: 'date_search_get'
  post '/date_search', to: 'nav#date_search_post', as: 'date_search_post'

  get '/nav/test', to: 'nav#test', as: 'nav_test'
  get '/user_guide', to: 'nav#user_guide', as: 'user_guide'
  get '/atom_tester/search', to: 'atom_feed_reader#search', as: 'atom_feed_search'

  get '/atom_tester', to: 'atom_feed_reader#index', as: 'atom_feed_tester'
  get '/atom_tester/prepopulate', to: 'atom_feed_reader#prepopulate', as: 'atom_feed_prepopulate'
  get '/atom_tester/read_current', to: 'atom_feed_reader#read_current', as: 'atom_feed_read_current'
  get '/atom_tester/json/:id', to: 'atom_feed_reader#read_json', as: 'atom_feed_read_json'
  get '/atom_tester/load_avalon_record/:id', to: 'atom_feed_reader#load_avalon_record', as: 'load_avalon_record'

  get '/people/new/entity/', to: 'people#new_entity', as: 'new_entity'

  get '/services/access_decisions_tester', to: 'test#test_access_decisions', as: 'test_access_decisions'
  get '/services/access_determination/:avalon_identifier', to: 'services#access_determination', as: 'access_determination'

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signoutg', to: 'sessions#destroy', via: :get

  resources :sessions, only: [:new, :destroy] do
    get :validate_login, on: :collection
  end

  get '/users/', to: 'user#index', as: 'users'
  get '/user/ldap_lookup', to: 'user#ldap_lookup', as: 'ldap_lookup'

  resources :works

  post '/avalon_items/access_decision', to: 'avalon_items#ajax_post_access_decision', as: 'ajax_avalon_item_access_decision'
  post '/avalon_items/ajax_needs_review', to: 'avalon_items#ajax_post_needs_review', as: 'ajax_post_needs_review'
  post '/avalon_items/ajax_reviewed', to: 'avalon_items#ajax_post_reviewed', as: 'ajax_post_reviewed'
  get '/avalon_items/ajax/calced_access_determination/:id', to: 'avalon_items#ajax_calced_access', as: 'ajax_avalon_item_calced_access'
  get '/avalon_items/cm/cm_all', to: 'avalon_items#cm_all_items', as: 'avalon_all_cm_items'
  get '/avalon_items/cm/cm_iu_default_only', to: 'avalon_items#cm_iu_default_only', as: 'avalon_items_cm_iu_default_only'
  get '/avalon_items/cm/cm_waiting_on_cl', to: 'avalon_items#cm_waiting_on_cl', as: 'avalon_items_cm_waiting_on_cl'
  get '/avalon_items/cm/cm_waiting_on_self', to: 'avalon_items#cm_waiting_on_self', as: 'avalon_items_cm_waiting_on_self'
  get '/avalon_items/cm/cm_access_determined', to: 'avalon_items#cm_access_determined', as: 'avalon_items_cm_access_determined'

  get '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder', as: 'ajax_people_adder_get'
  post '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder_post', as: 'ajax_people_adder_post'
  get '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter', as: 'ajax_people_setter_get'
  post '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter_post', as: 'ajax_people_setter_post'
  get '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter', as: 'ajax_work_setter_get'
  post '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter_post', as: 'ajax_work_setter_post'
  get '/ajax/people/ajax_work_person_form', to: "people#ajax_work_person_form", as: 'ajax_work_person_form'

  get '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder', as: 'ajax_work_adder_get'
  post '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder_post', as: 'ajax_work_adder_post'
  post 'avalon_items/:id/ajax_add_note', to: 'avalon_items#ajax_add_note', as: 'ajax_avalon_item_add_note'

  get '/avalon_items/ajax/cl_all', to: 'avalon_items#ajax_all_cl_items', as: 'ajax_avalon_cl_all'
  get '/avalon_items/ajax/cl_initial_review', to: 'avalon_items#ajax_cl_initial_review', as: 'avalon_items_cl_initial_review'
  get '/avalon_items/ajax/cl_waiting_on_cm', to: 'avalon_items#ajax_cl_waiting_on_cm', as: 'avalon_items_cl_waiting_on_cm'
  get '/avalon_items/ajax/cl_waiting_on_self', to: 'avalon_items#ajax_cl_waiting_on_self', as: 'avalon_items_cl_waiting_on_self'
  get '/avalon_items/ajax/cl_access_determined', to: 'avalon_items#ajax_cl_access_determined', as: 'avalon_items_cl_access_determined'

  get '/collections/', to: "collections#index", as: 'collections_index'
  post '/collections/', to: "collections#assign_access", as: 'collection_assign'
  get '/collection/:collection_name', to: "collections#collection_list", as: "collection_list"

  get '/contracts/ajax/new/:ai_id', to: 'contracts#ajax_new', as: 'ajax_new_contract'
  post '/contracts/ajax/create', to: 'contracts#ajax_create', as: 'ajax_create_contract'
  get '/contracts/ajax/edit/:id', to: 'contracts#ajax_edit', as: 'ajax_edit_contract'
  post '/contracts/ajax/update', to: 'contracts#ajax_update', as: 'ajax_update_contract'
  get '/contracts/ajax/show/:id', to: 'contracts#ajax_show', as: 'ajax_show_contract'

  get 'recordings/ajax/edit/:id', to: 'recordings#ajax_edit', as: 'ajax_edit_recording'
  get 'recordings/ajax/show/:id', to: 'recordings#ajax_show', as: 'ajax_show_recording'

  get '/people/ajax/new', to: 'people#ajax_new_person', as: 'ajax_new_person'
  get '/people/ajax/autocomplete', to: 'people#ajax_autocomplete', as: 'people_ajax_autocomplete'
  get '/people/ajax/autocomplete_company', to: "people#ajax_autocomplete_company", as: "people_ajax_autocomplete_company"
  get '/people/ajax/edit/:id', to: 'people#ajax_edit_person', as: 'ajax_edit_person'

  get '/performances/ajax/new/:recording_id', to: 'performances#ajax_new_performance', as: 'ajax_new_performance'
  get '/performances/ajax/edit/:id', to: 'performances#ajax_edit_performance', as: 'ajax_edit_performance'
  get '/performances/ajax/show/:id', to: 'performances#ajax_show_performance', as: 'ajax_Show_performance'
  post '/performances/ajax/access_determination', to: 'performances#ajax_access_determination', as: 'ajax_performance_access_determination'

  get '/tracks/ajax/new/:performance_id', to: 'tracks#ajax_new_track', as: 'ajax_new_track'
  get '/tracks/ajax/edit/:track_id', to: 'tracks#ajax_edit_track', as: 'ajax_edit_track'
  post '/tracks/ajax/access_determination', to: 'tracks#ajax_access_determination', as: 'ajax_track_access_determination'

  post '/users/ajax/set_user_unit/:username/:unit/:access', to: 'user#ajax_set_user_unit', as: 'ajax_set_user_unit'
  post '/users/ajax/set_user_cl/:username', to: 'users#ajax_toggle_cl', as: 'ajax_set_user_cl'
  get '/works/ajax/new', to: 'works#ajax_new_work', as: 'ajax_new_work'
  get '/works/ajax/:id', to: 'works#ajax_show', as: 'ajax_show_work'
  get '/work/ajax/autocomplete_title', to: 'works#ajax_autocomplete_title', as: 'work_ajax_autocomplete_title'
  get '/work/ajax/edit/:id', to: 'works#ajax_edit_work', as: 'ajax_edit_work'

  root 'nav#start'

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include AccessDeterminationHelper

  def index
    @collection_names = AvalonItem.where(pod_unit: UnitsHelper.human_readable_units_search(User.current_username)).order(:collection).group(:collection).count
  end

  def assign_access
    selected = params[:collections]&.keys

    if !selected || selected.size == 0
      flash.now[:warning] = "<p>You did not select any Collections</p>".html_safe
    elsif selected.size > 0
      if params[:access].blank? && params[:contract_type].blank? && params[:note].blank?
        flash.now[:warning] = "<p>You must specify at least an Access Determination, Contract Type, and/or Note</p>".html_safe
      else
        AvalonItem.transaction do
          ais = User.user_collection_ais(selected)
          @bad_ais = []
          @a =  process_access(ais)
          @b = process_legal_agreement(ais)
          @c = process_note(ais)
          if @a || @b || @c
            ais.each do |ai|
              ai.save!
            end
          end
        end
        if @bad_ais.size > 0
          flash.now[:warning] = "" if flash.now[:warning].nil?
          flash.now[:warning] << "<p>The following avalon items could not have their access determination set because it would be <b><i>less restrictive</i></b> than set by the copyright librarian</p>".html_safe
          flash.now[:warning] << "<p>#{@bad_ais.collect { |ba| ba.title }.join(" | ")}</p>".html_safe
        end
        if @a
          create_flash_now_notice
          flash.now[:notice] << "<p>The access determination was updated for all avalon items in the selected collection(s)</p>".html_safe
        end
        if @b
          create_flash_now_notice
          flash.now[:notice] << "<p>The specified legal agreement has been added to all avalon items in the selected collection(s)</p>".html_safe
        end
        if @c
          create_flash_now_notice
          flash.now[:notice] << "<p>The specified note was added to all avalon items in the selected collection(s)</p>".html_safe
        end
      end
    end



    @collection_names = AvalonItem.where(pod_unit: UnitsHelper.human_readable_units_search(User.current_username)).order(:collection).group(:collection).count
    render "index"
  end
  def collection_list
    @avalon_items = User.user_collection_ais(params[:collection_name])
    @people = []
    @works = []
    render 'nav/search'
  end

  private
  # parses the params hash and if an access determination is present, assigned it to the list of avalon_items, barring
  # any business logic rules, and returns true. Returns false if no access determination is present in the params hash or
  # an access determination could not be created because of business logic rules.
  def process_access(avalon_items)
    # lots to be done here: first check that collection manager is not trying to set access wider than copyright librarian has set
    unless params[:access].blank?
      @access = PastAccessDecision.new(decision: params[:access], changed_by: User.current_username, copyright_librarian: false)
      avalon_items.each do |ai|
        begin
          pad = @access.dup
          last = ai.last_copyright_librarian_access_decision
          # this comparison currently raises an exception when the access determination is less restrictive
          # FIXME: change this so that it returns true/false and does not raise the exception
          if last.nil? || is_more_restrictive_than?(pad, last)
            pad.avalon_item = ai
            ai.current_access_determination = pad
            ai.clear_all_reasons
            if pad.decision == AccessDeterminationHelper::RESTRICTED_ACCESS
              ai.reason_feature_film = !params[:restricted][:reason_feature_film].nil?
              ai.reason_licensing_restriction = !params[:restricted][:reason_licensing_restriction].nil?
              ai.reason_ethical_privacy_considerations = !params[:restricted][:reason_ethical_privacy_considerations].nil?
            elsif pad.decision == AccessDeterminationHelper::WORLD_WIDE_ACCESS
              ai.reason_iu_owned_produced = !params[:worldwide][:reason_iu_owned_produced].nil?
              ai.reason_public_domain = !params[:worldwide][:reason_public_domain].nil?
            ai.reason_license = !params[:worldwide][:reason_license].nil?
            elsif pad.decision == AccessDeterminationHelper::IU_ACCESS
              ai.reason_in_copyright = !params[:iu].nil? && !params[:iu][:reason_in_copyright].nil?
            end
            if pad.decision == AccessDeterminationHelper::DEFAULT_ACCESS
              ai.review_state = AccessDeterminationHelper::DEFAULT_ACCESS
            else
              ai.review_state = AvalonItem::REVIEW_STATE_ACCESS_DETERMINED
            end
            pad.save
          end
        rescue => e
          @bad_ais << ai
        end
      end
      true
    else
      false
    end
  end

  def process_legal_agreement(avalon_items)
    unless params[:contract_type].blank?
      @contract = Contract.new(
        contract_type: params[:contract_type],
        date_edtf_text: (params[:end_date].blank? ? nil : params[:end_date]),
        perpetual: params[:perpetual].blank? ? nil : params[:perpetual],
        notes: params[:agreement_notes].blank? ? nil : params[:agreement_notes])

      avalon_items.each do |ai|
        con = @contract.dup
        con.avalon_item = ai
        con.save
      end
    end
  end

  def process_note(avalon_items)
    unless params[:note].blank?
      @note = AvalonItemNote.new(text: params[:note], creator: User.current_username)
      avalon_items.each do |ai|
        note = @note.dup
        note.avalon_item = ai
        note.save
      end
    end
  end

  def create_flash_now_notice
    flash.now[:notice] = "" if flash.now[:notice].nil?
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/index.html.erb
<% if flash.now[:warning] %>
  <div class="rvt-alert rvt-alert--danger" role="alert" aria-labelledby="error-alert-title">
    <h1 class="rvt-alert__title" id="danger-alert-title">Invalid Select</h1>
    <%= flash.now[:warning].html_safe %>
  </div>
<% end %>
<% if flash.now[:notice] %>
  <div class="rvt-alert rvt-alert--success rvt-m-bottom-md" role="alertdialog" aria-labelledby="success-alert-title">
    <h1 class="rvt-alert__title" id="success-alert-title">The following updates were successful:</h1>
    <%= flash.now[:notice].html_safe %>
    <button type="button" class="rvt-alert__dismiss" data-alert-close>
      <span class="v-hide">Dismiss this alert</span>
      <svg aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
        <path fill="currentColor" d="M9.41,8l5.29-5.29a1,1,0,0,0-1.41-1.41L8,6.59,2.71,1.29A1,1,0,0,0,1.29,2.71L6.59,8,1.29,13.29a1,1,0,1,0,1.41,1.41L8,9.41l5.29,5.29a1,1,0,0,0,1.41-1.41Z"/>
      </svg>
    </button>
  </div>
<% end %>

<%= form_tag "/collections", method: :post, id: "mass_form" do %>
  <p>Bulk assign Access Determination, Legal Agreement, and/or Note to selected Collection Avalon Items</p>
  <div class="access_div">
    <label for=access>Access Determination:</label>
    <%= select_tag :access, options_for_select(AccessDeterminationHelper::ACCESS_DECISIONS.collect{|a| [a,a]}), include_blank: true  %>
    <div class="">
      <label for=access>Access Determination Reason</label><br>
      <div class="reasons_panels">
        <div id="restricted_reasons" class="reasons_div">
          <b class="access_warning">You must select one or more reasons below to save your Access Determination.</b>
          <ul class="rvt-plain-list" id="reasons_restricted">
            <li>
              <%= check_box_tag "restricted[reason_ethical_privacy_considerations]", "", checked = false, { class: "reason_checkbox restricted_reason" } %>
              <label for="restricted_reason_ethical_privacy_considerations">Ethical/Privacy Considerations</label>
            </li>
            <li>
              <%= check_box_tag "restricted[reason_feature_film]", "", checked = false, { class: "reason_checkbox restricted_reason" } %>
              <label for="restricted_reason_feature_film">Feature Film</label>
            </li>
            <li>
              <%= check_box_tag "restricted[reason_licensing_restriction]", "", checked = false, { class: "reason_checkbox restricted_reason" } %>
              <label for="restricted_reason_licensing_restriction">Licensing Restriction</label>
            </li>
          </ul>
        </div>
        <div id="iu_only_reasons" class="reasons_div">
          <ul class="rvt-plain-list" id="reasons_iu_only">
            <li>
              <%= check_box_tag "iu[reason_in_copyright]", "", checked = false, { class: "reason_checkbox iu_reason" } %>
              <label for="iu_reason_in_copyright">In Copyright</label>
            </li>
          </ul>
        </div>
        <div id="default_reasons" class="reasons_div">
        </div>
        <div id="worldwide_reasons" class="reasons_div">
          <b class="access_warning">You must select one or more reasons below to save your Access Determination.</b>
          <ul class="rvt-plain-list" id="reasons_worldwide">
            <li>
              <%= check_box_tag "worldwide[reason_iu_owned_produced]", "", checked = false, { class: "reason_checkbox worldwide_reason" } %>
              <label for="worldwide_reason_iu_owned_produced">IU Owned/Produced</label>
            </li>
            <li>
              <%= check_box_tag "worldwide[reason_license]", "", checked = false, { class: "reason_checkbox worldwide_reason" } %>
              <label for="worldwide_reason_license">Legal Agreement</label>
            </li>
            <li>
              <p class="red_700"><i>Public Domain cannot be chosen as a reason when setting an access level for a Collection.
                The required metadata must be entered in the Structured Metadata section of each Avalon Item in the Collection.</i></p>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="access_div " >
		<div class="legal_agreement">
			<h5>Legal Agreement</h5>
			<label for="agreement">Agreement Type</label> <%= select_tag :contract_type, options_for_select([['License'],['Contract'],['Policy'],['Deed of Gift'],['Other']]), include_blank: true %>
			<label for="date">End Date</label> <%= text_field_tag :end_date, nil, { class: 'edtf', "placeholder" => "YYYY/MM/DD (EDTF)" } %><span class="red_700 req">&nbsp;*</span>
			<label for="contract_perpetual">Perpetual?</label><%= select_tag :perpetual, options_for_select([['Yes', true],['No', false]]), { include_blank: '' } %><span class="red_700 req">&nbsp;*</span>
			<label for="notes">Notes</label> <%= text_area_tag :agreement_notes %>
		</div>
  </div>
  <div class="access_div">
    <label for="note">Avalon Item Note</label><%= text_area_tag :note %>
  </div>
  <div class="clear">
    <%= submit_tag "Submit", id: "submit_button" %>
  </div>
  <h4 class="clear">Collections</h4>
  <div>
    <ul class="rvt-plain-list">
      <% @collection_names.keys.each do |cn| %>
        <li class="rvt-checkbox-wrapper rvt-m-right-md">
          <%= check_box_tag "collections[#{cn}]", "#{cn}", false, class: "collection_checkbox" %>
          <%= label_tag "#{"collections_"+cn}", "#{cn}"  do %>
            <%= link_to "#{cn} (#{@collection_names[cn]})", collection_list_path(cn) %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function() {
		hookEdtfValidation();
		$("#access").change(function() {
      selectReasonsDiv()
    });
		$("#contract_type").change(function() {
			let val = $("#contract_type > option:selected").val();
			if (val === "") {
				$(".req").hide();
			} else {
				$(".req").show();
			}
		})

		$("#mass_form").submit(function(e) {
			if (!collectionSelected()) {
				e.preventDefault();
				e.stopPropagation();
				swal.fire({
          title: "Collection Required",
          text: "You must select one or more collections below to make a bulk assignment."
        })
      }
			if (!reasonChecked()) {
				e.stopPropagation();
				e.preventDefault();
				swal.fire({
          title: "Reason Required",
          text: "You must specify a reason for " + getAccessDetermination()
        })
      } else {
        let ad = getAccessDetermination();
        if (ad === "<%= AccessDeterminationHelper::WORLD_WIDE_ACCESS %>") {
	        // if legal agreement is checked there must be one that will be created (the bare minimum if an agreement type)
	        if ($("#worldwide_reason_license").prop("checked") && !legalAgreementValid()) {
		        e.stopPropagation();
						e.preventDefault();
		        swal.fire({
			        title: "Legal Agreement Required",
			        text: "You must enter all required fields in the Legal Agreement section that support Worldwide Access."
		        })
	        }
        }
      }
			if (anyLegalPresent() && !legalAgreementValid()) {
				e.stopPropagation();
				e.preventDefault();
				swal.fire({
					title: "Invalid Legal Agreement",
					text: "You must enter all required fields in the Legal Agreement section that support Worldwide Access"
				})
			}
    })
  });

  function collectionSelected() {
		return $(".collection_checkbox:checked").size() > 0;
  }

	// validates entered data in the legal agreement portion of the form
	function legalAgreementValid() {
		let ct = $("#contract_type option:selected").val();
		return ct !== null && ct !== "" && validEdtfDate($("#end_date").val()) !== "" && $("#perpetual option:selected").size() > 0 && $("#perpetual option:selected").val() !== "";
  }

	// checks whether any of the legal agreement form items have entered data
	function anyLegalPresent() {
		let ct = $("#contract_type option:selected").val()
		return (ct !== null && ct !== "") || $("#end_date").val() !== "" || ($("#perpetual option:selected").size() > 0 && $("#perpetual option:selected").val() !== "");
	}

	function reasonChecked() {
		let ad = getAccessDetermination();
		if (ad === "<%= AccessDeterminationHelper::WORLD_WIDE_ACCESS %>") {
			return $(".worldwide_reason:checked").size() > 0
    } else if (ad === "<%= AccessDeterminationHelper::RESTRICTED_ACCESS %>") {
			return $(".restricted_reason:checked").size() > 0
    } else {
      return true;
    }
  }

	function getAccessDetermination() {
		return $( "#access option:selected" ).text();
  }

  function selectReasonsDiv() {
	  let access = getAccessDetermination();
	  //clear previous reasons on access level change
    $('.reason_checkbox').removeAttr("checked");

	  switch(access) {
		  case "<%= AccessDeterminationHelper::RESTRICTED_ACCESS %>":
			  $('#iu_only_reasons').hide();
			  $("#default_reasons").hide();
			  $("#worldwide_reasons").hide();
			  $("#restricted_reasons").show();

			  break;
		  case "<%= AccessDeterminationHelper::IU_ACCESS %>":
			  $("#worldwide_reasons").hide();
			  $("#restricted_reasons").hide();
			  $("#default_reasons").hide();
			  $('#iu_only_reasons').show()
			  break;
		  case "<%= AccessDeterminationHelper::DEFAULT_ACCESS %>":
			  $("#restricted_reasons").hide();
			  $("#worldwide_reasons").hide();
			  $("#default_reasons").show();
			  $('#iu_only_reasons').hide()
			  break;
		  case "<%= AccessDeterminationHelper::WORLD_WIDE_ACCESS %>":
			  $('#iu_only_reasons').hide();
			  $("#default_reasons").hide();
			  $("#restricted_reasons").hide();
			  $("#worldwide_reasons").show();
			  break;
		  default:
			  swal.fire({
				  title: "Access Determination Error",
				  text: "Access was set to unknown value: "+access
			  });
	  }
  }

</script>