config/routes.rb
Rails.application.routes.draw do
  resources :avalon_items
  resources :avalon_item_notes, only: [:new, :create]
  resources :people
  resources :performances
  resources :performance_notes, only: [:new, :create]
  resources :policies
  resources :recording_contributors
  resources :recording_notes, only: [:new, :create]
  resources :recordings
  resources :tracks
  resources :contracts

  get '/nav/search', to: 'nav#search', as: "search"
  get '/date_search', to: 'nav#date_search_get', as: 'date_search_get'
  post '/date_search', to: 'nav#date_search_post', as: 'date_search_post'

  get '/nav/test', to: 'nav#test', as: 'nav_test'
  get '/user_guide', to: 'nav#user_guide', as: 'user_guide'
  get '/atom_tester/search', to: 'atom_feed_reader#search', as: 'atom_feed_search'

  get '/atom_tester', to: 'atom_feed_reader#index', as: 'atom_feed_tester'
  get '/atom_tester/prepopulate', to: 'atom_feed_reader#prepopulate', as: 'atom_feed_prepopulate'
  get '/atom_tester/read_current', to: 'atom_feed_reader#read_current', as: 'atom_feed_read_current'
  get '/atom_tester/json/:id', to: 'atom_feed_reader#read_json', as: 'atom_feed_read_json'
  get '/atom_tester/load_avalon_record/:id', to: 'atom_feed_reader#load_avalon_record', as: 'load_avalon_record'

  get '/people/new/entity/', to: 'people#new_entity', as: 'new_entity'

  get '/services/access_decisions_tester', to: 'test#test_access_decisions', as: 'test_access_decisions'
  get '/services/access_determination/:avalon_identifier', to: 'services#access_determination', as: 'access_determination'

  match '/signin', to: 'sessions#new', via: :get
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signoutg', to: 'sessions#destroy', via: :get

  resources :sessions, only: [:new, :destroy] do
    get :validate_login, on: :collection
  end

  get '/users/', to: 'user#index', as: 'users'
  get '/user/ldap_lookup', to: 'user#ldap_lookup', as: 'ldap_lookup'

  resources :works

  post '/avalon_items/access_decision', to: 'avalon_items#ajax_post_access_decision', as: 'ajax_avalon_item_access_decision'
  post '/avalon_items/ajax_needs_review', to: 'avalon_items#ajax_post_needs_review', as: 'ajax_post_needs_review'
  post '/avalon_items/ajax_reviewed', to: 'avalon_items#ajax_post_reviewed', as: 'ajax_post_reviewed'
  get '/avalon_items/ajax/calced_access_determination/:id', to: 'avalon_items#ajax_calced_access', as: 'ajax_avalon_item_calced_access'
  get '/avalon_items/cm/cm_all', to: 'avalon_items#cm_all_items', as: 'avalon_all_cm_items'
  get '/avalon_items/cm/cm_iu_default_only', to: 'avalon_items#cm_iu_default_only', as: 'avalon_items_cm_iu_default_only'
  get '/avalon_items/cm/cm_waiting_on_cl', to: 'avalon_items#cm_waiting_on_cl', as: 'avalon_items_cm_waiting_on_cl'
  get '/avalon_items/cm/cm_waiting_on_self', to: 'avalon_items#cm_waiting_on_self', as: 'avalon_items_cm_waiting_on_self'
  get '/avalon_items/cm/cm_access_determined', to: 'avalon_items#cm_access_determined', as: 'avalon_items_cm_access_determined'

  get '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder', as: 'ajax_people_adder_get'
  post '/avalon_items/:id/ajax_people_adder', to: 'avalon_items#ajax_people_adder_post', as: 'ajax_people_adder_post'
  get '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter', as: 'ajax_people_setter_get'
  post '/avalon_items/:id/ajax_people_setter/:pid', to: 'avalon_items#ajax_people_setter_post', as: 'ajax_people_setter_post'
  get '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter', as: 'ajax_work_setter_get'
  post '/avalon_items/:id/ajax_work_setter/:wid', to: 'avalon_items#ajax_work_setter_post', as: 'ajax_work_setter_post'
  get '/ajax/people/ajax_work_person_form', to: "people#ajax_work_person_form", as: 'ajax_work_person_form'

  get '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder', as: 'ajax_work_adder_get'
  post '/avalon_items/:id/ajax_work_adder', to: 'avalon_items#ajax_work_adder_post', as: 'ajax_work_adder_post'
  post 'avalon_items/:id/ajax_add_note', to: 'avalon_items#ajax_add_note', as: 'ajax_avalon_item_add_note'

  get '/avalon_items/ajax/cl_all', to: 'avalon_items#ajax_all_cl_items', as: 'ajax_avalon_cl_all'
  get '/avalon_items/ajax/cl_initial_review', to: 'avalon_items#ajax_cl_initial_review', as: 'avalon_items_cl_initial_review'
  get '/avalon_items/ajax/cl_waiting_on_cm', to: 'avalon_items#ajax_cl_waiting_on_cm', as: 'avalon_items_cl_waiting_on_cm'
  get '/avalon_items/ajax/cl_waiting_on_self', to: 'avalon_items#ajax_cl_waiting_on_self', as: 'avalon_items_cl_waiting_on_self'
  get '/avalon_items/ajax/cl_access_determined', to: 'avalon_items#ajax_cl_access_determined', as: 'avalon_items_cl_access_determined'

  get '/collections/', to: "collections#index", as: 'collections_index'
  post '/collections/', to: "collections#assign_access", as: 'collection_assign'
  get '/collection/:collection_name', to: "collections#collection_list", as: "collection_list"

  get '/contracts/ajax/new/:ai_id', to: 'contracts#ajax_new', as: 'ajax_new_contract'
  post '/contracts/ajax/create', to: 'contracts#ajax_create', as: 'ajax_create_contract'
  get '/contracts/ajax/edit/:id', to: 'contracts#ajax_edit', as: 'ajax_edit_contract'
  post '/contracts/ajax/update', to: 'contracts#ajax_update', as: 'ajax_update_contract'
  get '/contracts/ajax/show/:id', to: 'contracts#ajax_show', as: 'ajax_show_contract'

  get 'recordings/ajax/edit/:id', to: 'recordings#ajax_edit', as: 'ajax_edit_recording'
  get 'recordings/ajax/show/:id', to: 'recordings#ajax_show', as: 'ajax_show_recording'

  get '/people/ajax/new', to: 'people#ajax_new_person', as: 'ajax_new_person'
  get '/people/ajax/autocomplete', to: 'people#ajax_autocomplete', as: 'people_ajax_autocomplete'
  get '/people/ajax/autocomplete_company', to: "people#ajax_autocomplete_company", as: "people_ajax_autocomplete_company"
  get '/people/ajax/edit/:id', to: 'people#ajax_edit_person', as: 'ajax_edit_person'

  get '/performances/ajax/new/:recording_id', to: 'performances#ajax_new_performance', as: 'ajax_new_performance'
  get '/performances/ajax/edit/:id', to: 'performances#ajax_edit_performance', as: 'ajax_edit_performance'
  get '/performances/ajax/show/:id', to: 'performances#ajax_show_performance', as: 'ajax_Show_performance'
  post '/performances/ajax/access_determination', to: 'performances#ajax_access_determination', as: 'ajax_performance_access_determination'

  get '/tracks/ajax/new/:performance_id', to: 'tracks#ajax_new_track', as: 'ajax_new_track'
  get '/tracks/ajax/edit/:track_id', to: 'tracks#ajax_edit_track', as: 'ajax_edit_track'
  post '/tracks/ajax/access_determination', to: 'tracks#ajax_access_determination', as: 'ajax_track_access_determination'

  post '/users/ajax/set_user_unit/:username/:unit/:access', to: 'user#ajax_set_user_unit', as: 'ajax_set_user_unit'
  post '/users/ajax/set_user_cl/:username', to: 'users#ajax_toggle_cl', as: 'ajax_set_user_cl'
  get '/works/ajax/new', to: 'works#ajax_new_work', as: 'ajax_new_work'
  get '/works/ajax/:id', to: 'works#ajax_show', as: 'ajax_show_work'
  get '/work/ajax/autocomplete_title', to: 'works#ajax_autocomplete_title', as: 'work_ajax_autocomplete_title'
  get '/work/ajax/edit/:id', to: 'works#ajax_edit_work', as: 'ajax_edit_work'

  root 'nav#start'

end

app/models/person.rb
class Person < ActiveRecord::Base
  before_save :edtf_dates
  has_many :person_nationalities
  has_many :nationalities, through: :person_nationalities

  has_many :person_iu_affiliations
  has_many :iu_affiliations, through: :person_iu_affiliations

  has_many :recording_contributor_people
  has_many :recordings, through: :recording_contributor_people

  has_many :performance_contributor_people
  has_many :performances, through: :performance_contributor_people

  has_many :track_contributor_people
  has_many :contributions, -> { where "interviewer = true OR interviewee = true OR conductor = true OR performer = true" }, class_name: "TrackContributorPerson"
  has_many :tracks, through: :contributions

  has_many :avalon_items, through: :recordings

  has_many :work_contributor_people
  has_many :works, through: :work_contributor_people

  before_save :clear_person_entity

# for json population
#   attr_accessor :value
#   attr_accessor :label

  RECORDING_CONTRIBUTOR_ROLES_KEY = "recording"
  PERFORMANCE_CONTRIBUTOR_ROLES_KEY = "performance"
  TRACK_CONTRIBUTOR_ROLES_KEY = "track"
  WORK_CONTRIBUTOR_ROLES_KEY = "work"
  ROLES = {
      RECORDING_CONTRIBUTOR_ROLES_KEY => ["Depositor (R)", "Recording Producer (R)"],
      TRACK_CONTRIBUTOR_ROLES_KEY => ["Interviewer (P)", "Performer (P)", "Conductor (P)", "Interviewee (P)"],
      WORK_CONTRIBUTOR_ROLES_KEY => ["Contributor (W)", "Principle Creator (W)"]
  }
  ALL_ROLES = Person::ROLES.keys.collect{|k| Person::ROLES[k]}.flatten.sort

  searchable do
    text :aka
    text "name" do
      if entity?
        "#{company_name}"
      else
        "#{full_name}"
      end
    end
  end

  def self.solr_search(term)
    p = Person.search do fulltext term end
    p.results
  end

  def name
    "#{first_name} #{last_name}"
  end
  def full_name_last_first
    "#{last_name}, #{first_name}#{middle_name.blank? ? '' : " #{middle_name}"}"
  end
  def full_name
    "#{first_name}#{middle_name.blank? ? '' : " "+middle_name} #{last_name}"
  end

  def label
    self.entity? ? company_name : full_name
  end
  def value
    id
  end

  def birth_death_text
    if date_of_birth_edtf.blank? && date_of_death_edtf.blank?
      ""
    else
      "#{date_of_birth_edtf} - #{date_of_death_edtf}"
    end
  end

  def recording_producer?(r_id)
    recording_contributor_people.where(recording_id: r_id, recording_producer: true).size > 0
  end
  def recording_depositor?(r_id)
    recording_contributor_people.where(recording_id: r_id, recording_depositor: true).size > 0
  end

  def track_interviewer?(t_id)
    track_contributor_people.where(track_id: t_id, interviewer: true).size > 0
  end
  def track_performer?(t_id)
    track_contributor_people.where(track_id: t_id, performer: true).size > 0
  end
  def track_conductor?(t_id)
    track_contributor_people.where(track_id: t_id, conductor: true).size > 0
  end
  def track_interviewee?(t_id)
    track_contributor_people.where(track_id: t_id, interviewee: true).size > 0
  end

  def track_contributor?(t_id)
    track_contributor_people.where(track_id: t_id, contributor: true).size > 0
  end

  def as_json(options)
    super(methods: [:label, :value])
  end

  # This method ensures that when an EDTF text date is modified (added, changed or removed), that the underlying
  # DB Date reflects that
  def edtf_dates
    date = Date.edtf(date_of_birth_edtf&.gsub('/', '-'))
    self.date_of_birth = date
    puts "Set date_of_birth to #{date}, calling self.date_of_birth: #{self.date_of_birth}"

    date = Date.edtf(date_of_death_edtf&.gsub('/', '-'))
    self.date_of_death = date
    puts "Set date_of_death to #{date}, calling self.date_of_death: #{self.date_of_death}"
  end

# if a person is changed to an entity, or vice versa, clear the no-longer-relevant fields
  def clear_person_entity
    if self.entity?
      first_name = middle_name = last_name = date_of_birth = date_of_death = date_of_birth_edtf =
        date_of_death_edtf = place_of_birth = nil
    else
      company_name = entity_nationality = nil
    end
  end


end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.where(entity: false).order(:last_name)
    @entities = Person.where(entity: true).order(:company_name)
  end

  # GET /people/1
  # GET /people/1.json
  def show
    #render 'people/_ajax_show'
    render 'people/show'
  end

  # GET /people/new
  def new
    @person = Person.new(entity: false)
  end

  def new_entity
    @person = Person.new(entity: true)
    render 'people/new'
  end

  # GET /people/1/edit
  def edit
  end

  def ajax_edit_person
    render partial: 'people/ajax_edit_person'
  end

  # GET /people/
  def ajax_autocomplete
    @hits = Person.where("last_name like ?", "%#{params[:term]}%")
    render json: @hits
  end

  def ajax_autocomplete_company
    @hits = Person.where("company_name like ?", "%#{params[:term]}%")
    render json: @hits
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
    # hidden field tag for entity is sent as text so person_params does not correctly assign it.
    @person.entity = params["entity"] == "true"
    respond_to do |format|
      if @person.save
        if params[:avalon_item_id]
          @avalon_item = AvalonItem.find(params[:avalon_item_id])
          AvalonItemPerson.new(person_id: @person.id, avalon_item_id: params[:avalon_item_id].to_i).save
        end
        format.html { redirect_to people_path }
        format.js {}
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    respond_to do |format|
      if @person.avalon_items.size + @person.works.size> 0
        format.html { redirect_to people_url, notice: "The Person/Entity <i>#{@person.entity? ? @person.company_name : @person.full_name}</i> could not be destroyed because it is associated with Avalon Items or Works" }
      else
        @person.destroy
        format.html { redirect_to people_url, notice: "The Person/Entity <i>#{@person.entity? ? @person.company_name : @person.full_name}</i> was successfully destroyed." }
      end
    end
  end

  def ajax_new_person
    @person = Person.new(last_name: params[:last_name], first_name: params[:first_name])
    @ajax = true
    render partial: 'people/form'
  end

  def ajax_show
    @person = Person.find(params[:id])
    render partial: 'person/ajax_show'
  end

  def ajax_work_person_form
    @person = Person.find(params[:id])
    render partial: 'ajax_work_person_form'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(
          :first_name, :middle_name, :last_name, :date_of_birth_edtf, :date_of_death_edtf, :place_of_birth,
          :authority_source, :aka, :notes, :authority_source_url, :entity, :company_name, :entity_nationality
      )
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_ajax_edit_person.js.erb
setPerson(<%= params[:id] %>, true)

app/views/people/_ajax_show.html.erb
<div class="rvt-grid">
  <% if @person.entity? %>
    <div class="rvt-grid__item-12">
      <h4 class="red_700"><%= @person.company_name %></h4>
    </div>
    <div class="rvt-grid__item-4-md-up">
      <label for="alternative_titles">Nationality</label>
      <%= @person.entity_nationality %>
    </div>
  <% else %>
    <div class="rvt-grid__item-12">
      <h4 class="red_700"><%= @person.full_name %></h4>
    </div>
    <div class="rvt-grid__item-4-md-up">
      <label for="alternative_titles">Date of Birth</label>
      <%= @person.date_of_birth_edtf %>
    </div>
    <div class="rvt-grid__item-4-md-up">
      <label for="publication_year">Date of Death</label>
      <%= @person.date_of_death_edtf %>
    </div>
    <div class="rvt-grid__item-4-md-up">
      <label for="authority_source">Place of Birth</label>
      <%= @person.place_of_birth %>
    </div>
  <% end %>
  <div class="rvt-grid__item-4-md-up">
    <label for="authority_source">AKA</label>
    <%= @person.aka %>
  </div>
  <div class="rvt-grid__item-4-md-up">
    <label for="authority_source">Authority Source</label>
    <%= @person.authority_source %>
  </div>
  <div class="rvt-grid__item-4-md-up">
    <label for="authority_source_url">Authority Source URL</label>
    <%= link_to "#{@person.authority_source_url.truncate(25)}", @person.authority_source_url, target: "_blank" unless @person.authority_source_url.blank?%>
  </div>
  <div class="rvt-grid__item-12">
    <label for="notes">Notes</label>
    <%= @person.notes %>
  </div>
</div>

app/views/people/_ajax_work_person_form.html.erb
<div id="work_person_<%= @person.id %>" class="work_person">
  <div class="name">
    <b class="red_700"><%= @person.full_name %></b>
  </div>
  <div class="roles">
    <input class="creator_checkbox" type="checkbox" name="<%= "work_people[#{@person.id}]principle_creator" %>"
           id="<%= "principle_creator_#{@person.id}" %>" <%= 'checked' if @work&.principle_creator?(@person.id) %>>
    <label for="<%= "principle_creator_#{@person.id}" %>">Principle Creator</label>
    <input class="contributor_checkbox" type="checkbox" name="<%= "work_people[#{@person.id}]contributor" %>"
           id="<%= "contributor_#{@person.id}" %>" <%= 'checked' if @work&.contributor?(@person.id) %>>
    <label for="<%= "contributor_#{@person.id}" %>">Contributor</label>
  </div>
  <div class="actions">
    <button class="rvt-button workPersonRemover" type="button" data-remove-target="work_person_<%= @person.id %>" >Remove</button>
  </div>
</div>

app/views/people/_autocomplete_entity_tooltip.html.erb
<div id="autocomplete_company_summary" class="rvt-grid entity_ac_tooltip">
  <h4 class="red_700" id="ac_company_name"></h4>
  <div>
    <label for="nationality">Company Nationality</label>
    <span id="ac_nat"></span>
  </div>
  <div>
    <label for="authority_source">AKA</label>
    <span id="ac_company_aka"></span>
  </div>
  <div>
    <label for="authority_source_url">Authority Source</label>
    <span id="ac_company_auth"></span>
  </div>
  <div>
    <label for="authority_source_url">Authority Source URL</label>
    <span id="ac_company_auth_url"></span>
  </div>
  <div>
    <label for="notes">Notes</label>
    <span id="ac_company_notes"></span>
  </div>
</div>

app/views/people/_autocomplete_person_tooltip.html.erb
<div id="autocomplete_summary" class="rvt-grid person_ac_tooltip">
  <h4 class="red_700" id="ac_full_name"></h4>
  <div>
    <label for="alternative_titles">Date of Birth</label>
    <span id="ac_dob"></span>
  </div>
  <div>
    <label for="publication_year">Date of Death</label>
    <span id="ac_dod"></span>
  </div>
  <div>
    <label for="authority_source">Place of Birth</label>
    <span id="ac_pob"></span>
  </div>
  <div>
    <label for="authority_source">AKA</label>
    <span id="ac_aka"></span>
  </div>
  <div>
    <label for="authority_source_url">Authority Source</label>
    <span id="ac_auth"></span>
  </div>
  <div>
    <label for="authority_source_url">Authority Source URL</label>
    <span id="ac_auth_url"></span>
  </div>
  <div>
    <label for="notes">Notes</label>
    <span id="ac_notes"></span>
  </div>
</div>

app/views/people/_autocomplete_work_person_tooltip.html.erb
<div id="autocomplete_work_person_summary" class="rvt-grid work_person_ac_tooltip">
  <h4 class="red_700" id="ac_full_name"></h4>
  <div>
    <label for="alternative_titles">Date of Birth</label>
    <span id="ac_dob"></span>
  </div>
  <div>
    <label for="publication_year">Date of Death</label>
    <span id="ac_dod"></span>
  </div>
  <div>
    <label for="authority_source">Place of Birth</label>
    <span id="ac_pob"></span>
  </div>
  <div>
    <label for="authority_source">AKA</label>
    <span id="ac_aka"></span>
  </div>
  <div>
    <label for="authority_source_url">Authority Source</label>
    <span id="ac_auth"></span>
  </div>
  <div>
    <label for="authority_source_url">Authority Source URL</label>
    <span id="ac_auth_url"></span>
  </div>
  <div>
    <label for="notes">Notes</label>
    <span id="ac_notes"></span>
  </div>
</div>

app/views/people/ajax_autocomplete.html.erb
<% @hits.to_json %>

app/views/people/create.js.erb
swal({
    title: "Person",
    html: "<p>A new Person was created with name: <i><%= @person.name %></i>"
});
$.ajax({
    url: '<%= ajax_avalon_item_rmd_metadata_path(@avalon_item.id) %>',
    success: function(result) {
        $('.rmd_metadata').html(result);
        hookListeners();
    },
    error: function() {
        swal("Something bad happened server side...")
    }
})

app/views/people/edit.html.erb
<h1>Editing Person</h1>
<%= render 'form' %>

app/views/people/index.html.erb
<p id="notice"><%= flash[:notice]&.html_safe %></p>
<h2>Listing People <%= button_to "Create New Person", new_person_path, method: :get %></h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date of Birth</th>
      <th>Date of Death</th>
      <th>Place of Birth</th>
      <th>Authority Source</th>
      <th>Authority Source URL</th>
      <th>AKA</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @people.each_with_index do |person, i| %>
      <tr class=<%= "#{i.odd? ? 'odd' : 'even'}" %>>
        <td><%= link_to  person.full_name_last_first, person, target: "_blank" %></td>
        <td><%= person.date_of_birth %></td>
        <td><%= person.date_of_death %></td>
        <td><%= person.place_of_birth %></td>
        <td><%= person.authority_source %></td>
        <td><%= link_to "#{person.authority_source_url}", person.authority_source_url unless person.authority_source_url.blank? %></td>
        <td></td>
        <td>
          <%= link_to 'Show', person %> <br>
          <%= link_to "Edit", edit_person_path(person) %>
          <% if person.avalon_items.size > 0 %>
            <br>
            <%= link_to "Delete", person, method: :delete %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2 class="rvt-m-top-xl">Listing Entities <%= button_to "Create New Entity", new_entity_path, method: :get %></h2>
<table>
  <thead>
  <tr>
    <th>Company Name</th>
    <th>Nationality</th>
    <th>Authority Source</th>
    <th>Authority Source URL</th>
    <th>AKA</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @entities.each_with_index do |person, i| %>
    <tr class=<%= "#{i.odd? ? 'odd' : 'even'}" %>>
      <td><%= person.company_name %></td>
      <td><%= person.entity_nationality %></td>
      <td><%= person.authority_source %></td>
      <td><%= link_to "#{person.authority_source_url}", person.authority_source_url, target: '_blank' unless person.authority_source_url.blank? %></td>
      <td></td>
      <td>
        <%= link_to 'Show', person %>
        <%= link_to "Edit", edit_person_path(person) %>
        <% if person.avalon_items.size > 0 %>
          <%= link_to 'Destroy', person, method: :delete %>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<%= link_to 'Back', people_path %>
<h1>New <%= @person.entity? ? "Entity" : "Person" %></h1>
<%= render 'form' %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>
<% if @person.entity? %>
  <h3>
    Company: <span class="avalon_item_title rvt-text-bold" style="color: #006298"><%= @person.company_name %></span>
  </h3>
  <table class="rvt-table-compact">
    <tbody>
      <tr>
        <th>Nationality</th>
        <td><%= @person.entity_nationality %></td>
      </tr>
      <tr>
        <th>Authority Source</th>
        <td><%= @person.authority_source %></td>
      </tr>
      <tr>
        <th>Authority Source URL</th>
        <td>
          <% unless @person.authority_source_url.blank? %>
            <%= link_to "#{@person.authority_source_url}", @person.authority_source_url, target: '_blank' unless @person.authority_source_url.blank? %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% else %>
  <h3>
    Person: <span class="avalon_item_title rvt-text-bold" style="color: #006298"><%= @person.full_name_last_first %></span>
  </h3>
  <table class="rvt-table-compact w_50">
    <tbody>
    <tr>
      <th class="vert_th">AKA</th>
      <td><%= @person.aka %></td>
    </tr>
    <tr>
      <th class="vert_th">Date of Birth</th>
      <td><%= @person.date_of_birth_edtf %></td>
    </tr>
    <tr>
      <th class="vert_th">Date of Death</th>
      <td><%= @person.date_of_death_edtf %></td>
    </tr>
    <tr>
      <th class="vert_th">Place of Birth</th>
      <td><%= @person.place_of_birth %></td>
    </tr>
    <tr>
      <th class="vert_th">Authority Source</th>
      <td><%= @person.authority_source %></td>
    </tr>
    <tr>
      <th class="vert_th">Authority Source URL</th>
      <td><%= link_to "#{@person.authority_source_url}", @person.authority_source_url, target: '_blank' unless @person.authority_source_url.blank?%></td>
    </tr>
    </tbody>
  </table>
<% end %>
<div class="notes">
  <b>Notes:</b> <%= @person.notes%>
</div>
<%= button_to "Edit", edit_person_path(@person), method: :get %>
<br><br>
<h3>Works this Person contributes to</h3>
<table>
  <tbody>
    <% @person.works.each do |w| %>
    <tr><td>
      <%= link_to "#{w.title}", work_path(w) %>
    </td></tr>
    <% end %>
  </tbody>
</table>
<br>
<h3>Avalon Items this Person contributes to</h3>
<table>
  <tbody>
  <% @person.avalon_items.each do |ai| %>
    <tr><td>
      <%= link_to "#{ai.title}", avalon_item_path(ai) %>
    </td></tr>
  <% end %>
  </tbody>
</table>